apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: noble
  namespace: {{ .Values.namespace }}
  labels:
    release: prometheus-stack
    app: noble
spec:
  namespaceSelector:
    matchNames:
      - nobled
  selector:
    matchLabels:
      app: noble
  podMetricsEndpoints:
    - port: prometheus
      interval: 30s
      relabelings:
        - sourceLabels: [ __meta_kubernetes_pod_node_name ]
          targetLabel: node
        - sourceLabels: [ __meta_kubernetes_pod_label_app ]
          targetLabel: app

